week1 databases assignement  complete
HackYourAssignment/databases-cohort47 pull request #9
Opened 2024-05-08 10:12 UTC by Hailemariam7

2024-05-15 10:50 UTC, codethenpizza requested changes
You're doing great. There are a few things to consider that can make your code even better:

- DRY Principle: Avoid repeating the same pattern multiple times by creating a helper function for your queries. This makes your code cleaner and easier to maintain.

- Data Integrity: Add "NOT NULL" constraints to columns where it makes sense to ensure that important fields always have values. This can help maintain data integrity and prevent potential issues.


Also, as I see there's no direct requirement to create tables and data via JS, but if you feel like you want a bit more challenge, you can execute your queries with JS code 🙂

2024-05-15 10:50 UTC, codethenpizza commented on Week1/Assignment/world.js
> +});
You get the right result, but using code. 
How would you do this only with query?

2024-05-15 10:50 UTC, codethenpizza commented on Week1/Assignment/studentMeeting.sql
> +);
One thing I noticed is that some of your columns don't have the "NOT NULL" constraint. Adding this constraint can help ensure data integrity by making sure that important fields always have a value.
 
Here is a suggestion on where you might want to add "NOT NULL":
```
invitee_name VARCHAR(255) NOT NULL  -- Names are usually required
```
What do you think, what are the other fields that sounds like suppose to be required?

2024-05-15 14:04 UTC, Hailemariam7 commented on Week1/Assignment/studentMeeting.sql
> +);
I have corrected it. Now meeting title, start_time and end_time among other columns have NOT NULL added.

2024-05-15 14:08 UTC, Hailemariam7 commented on Week1/Assignment/world.js
> +});
certainly, it is shorter with query. I have changed it.  thanks!

2024-05-15 14:56 UTC, Hailemariam7 commented on Week1/Assignment/world.js
> +);
I have tried to shorten it now by implement the connection.query in a separate function, I hope it is more readable now and cleaner.

2024-05-15 15:00 UTC, Hailemariam7 commented
Thank you very much for taking you valuable time to review this! I have implemented the feedbacks. I hope it good enough to be approved, but open for more feedback at the same time. I will make the PR now.

2024-05-16 11:38 UTC, codethenpizza approved these changes

2024-05-16 11:38 UTC, codethenpizza commented
Good job!

2024-05-16 14:31 UTC, Hailemariam7 commented
Thank you

2024-05-16 14:31 UTC, closed without merging